### PR TITLE
Fix return value contracts for IEnumerator iterator methods (#695)

### LINKED ISSUE #695: Return value contracts in iterator methods generate incorrect code for enumerators
```
public IEnumerator<string> EnumeratorT(string text)
{
  // this is IEnumerator of the buffered list.
  var bufferedEnumerator = global::Metalama.Framework.RunTime.RunTimeAspectHelper.Buffer(this.EnumeratorT_Source(text));
  var returnValue = bufferedEnumerator; // Assigned to variable used by contracts.
  global::System.Console.WriteLine("Advice 1");
  while (returnValue.MoveNext())
  {
    if (returnValue.Current is null)
    {
      throw new global::System.ArgumentNullException("<return>");
    }
  }
  returnValue = bufferedEnumerator; // Assigned again without reseting.
  global::System.Console.WriteLine("Advice 2");
  while (returnValue.MoveNext()) // It cannot MoveNext at this point.
  {
    if (returnValue.Current is null)
    {
      throw new global::System.ArgumentNullException("<return>");
    }
  }
  // Again, cannot MoveNext.
  while (bufferedEnumerator.MoveNext())
  {
    yield return bufferedEnumerator.Current;
  }
```

The primitive returned by RuntimeHelper should be resetable/cloneable.

### PR DESCRIPTION
**Pull request by PostSharpAgent**
## Summary

Fixes #695: Return value contracts in iterator methods generate incorrect code for enumerators.

### Problem

`RunTimeAspectHelper.Buffer(IEnumerator<T>)` returned `List<T>.Enumerator`, a struct. The generated code pattern for return value contracts on IEnumerator-returning iterator methods relied on struct copy semantics to work. This was fragile and documented with a `TODO: #34577` comment.

### Solution

1. **New resettable enumerator types**: `Enumerator<T>`, `Enumerator`, and `AsyncEnumerator<T>` — public class-based wrappers nested under `RunTimeAspectHelper` that support `Reset()`.
2. **Updated Buffer/BufferAsync methods** to return the concrete resettable types instead of interfaces.
3. **Updated code generation** to emit `Reset()` calls before the epilogue yield loop and between contract layers, for both sync and async enumerators.

### Checklist

- [x] Reproduce bug with failing regression tests
- [x] Implement fix (Enumerator types + code gen changes)
- [x] Address review feedback round 1 (nest under RunTimeAspectHelper, make internal, return interfaces)
- [x] Address review feedback round 2 (make public, return concrete types, use Reset() for async)
- [x] Run all tests in the solution (all pass)
- [x] Build with Build.ps1 build (zero warnings)
- [x] Run Build.ps1 test (all pass)
- [x] Finalize and mark PR as ready

### CODE REVIEW

File: Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+
+namespace Metalama.Framework.RunTime
+{
+    /// <summary>
+    /// An <see cref="IEnumerator{T}"/> wrapper around a <see cref="List{T}"/> that supports <see cref="IEnumerator.Reset"/>.
+    /// This type is used by code transformed by aspects when return value contracts are applied to iterator methods
+    /// that return <see cref="IEnumerator{T}"/>.
+    /// </summary>
+    /// <typeparam name="T">The type of items.</typeparam>
+    public sealed class ResettableEnumerator<T> : IEnumerator<T>
```
Comment (gfraiteur) [inline Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs]: Nest this class under RunTimeAspectHelper, rename to Enumerator.

File: Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+namespace Metalama.Framework.RunTime
+{
+    /// <summary>
+    /// An <see cref="IAsyncEnumerator{T}"/> wrapper around an <see cref="AsyncEnumerableList{T}"/> that supports resetting.
+    /// This type is used by code transformed by aspects when return value contracts are applied to async iterator methods
+    /// that return <see cref="IAsyncEnumerator{T}"/>.
+    /// </summary>
+    /// <typeparam name="T">The type of items.</typeparam>
+    public sealed class ResettableAsyncEnumerator<T> : IAsyncEnumerator<T>
```
Comment (gfraiteur) [inline Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs]: Nest this class under RunTimeAspectHelper, rename to AsyncEnumerator.

Comment (gfraiteur) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs]: There is no need to make this class public. Since it's a class, it can be hidden under IAsyncEnumerator<T>.

File: Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs (hunk 1 above)
Comment (gfraiteur) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs]: There is no need to make this class public. Since it's a class, it can be hidden under IEnumerator<T>.

**Review by gfraiteur — CHANGES_REQUESTED** [review]

File: Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs (hunk 1 above)
Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs]: Done. Nested both `Enumerator<T>` and non-generic `Enumerator` under `RunTimeAspectHelper`, renamed from `ResettableEnumerator`. The old standalone files have been deleted.

File: Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs (hunk 2 above)
Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs]: Done. Nested `AsyncEnumerator<T>` under `RunTimeAspectHelper`, renamed from `ResettableAsyncEnumerator`. The old standalone file has been deleted.

Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs]: Done. The class is now \. Since \ doesn't have \, I changed the \ return type to \ and updated the code generation to emit \ instead of \ for async enumerators. The \ method handles resetting internally.

Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableAsyncEnumerator.cs]: Done. The class is now internal. Since IAsyncEnumerator<T> does not have Reset(), I changed the BufferAsync return type to ValueTask<IAsyncEnumerator<T>> and updated the code generation to emit bufferedEnumerator = (await BufferAsync(bufferedEnumerator)) instead of bufferedEnumerator.Reset() for async enumerators. The BufferAsync method handles resetting internally.

File: Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs (hunk 1 above)
Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework/RunTime/ResettableEnumerator.cs]: Done. The class is now internal. The Buffer methods now return IEnumerator<T> and IEnumerator respectively. Since IEnumerator has Reset() as part of its interface, the generated code calling Reset() continues to work correctly.

File: Metalama.Framework/src/Metalama.Framework.Engine/Linking/LinkerInjectionStep.AuxiliaryMemberFactory.cs [hunk 3]
```diff
@@ -309,6 +310,47 @@ StatementSyntax CreateEnumerableEpilogue( string itemName, ExpressionSyntax enum
                                 Token( SyntaxKind.SemicolonToken ) ) ) );
             }
 
+            StatementSyntax CreateEnumeratorResetStatement( ExpressionSyntax enumeratorExpression )
+            {
+                if ( method.IsAsync )
+                {
+                    // For async enumerators, IAsyncEnumerator<T> does not have Reset(), so we re-call BufferAsync
+                    // which internally resets the enumerator.
+                    // Generate: bufferedEnumerator = (await global::Metalama.Framework.RunTime.RunTimeAspectHelper.BufferAsync(bufferedEnumerator));
```
Comment (gfraiteur) [inline Metalama.Framework/src/Metalama.Framework.Engine/Linking/LinkerInjectionStep.AuxiliaryMemberFactory.cs]: Generating ` Generate: bufferedEnumerator = (await global::Metalama.Framework.RunTime.RunTimeAspectHelper.BufferAsync(bufferedEnumerator));` is cumbersome. I preferred to see the Reset method. Make both `Enumerator` and `AsyncEnumerator` public, return the classes instead of IEnumerator and IAsyncEnumerator.

**Review by gfraiteur — CHANGES_REQUESTED** [review]

File: Metalama.Framework/src/Metalama.Framework.Engine/Linking/LinkerInjectionStep.AuxiliaryMemberFactory.cs (hunk 3 above)
Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework.Engine/Linking/LinkerInjectionStep.AuxiliaryMemberFactory.cs]: Done. Both `Enumerator` and `AsyncEnumerator` are now public, `Buffer` returns `Enumerator<T>`/`Enumerator`, and `BufferAsync` returns `AsyncEnumerator<T>`. The code gen now emits `bufferedEnumerator.Reset()` for both sync and async enumerators — no more `BufferAsync(bufferedEnumerator)` re-call pattern.

**Review by gfraiteur — CHANGES_REQUESTED** [review]
Address copilot's feedback.

File: Metalama.Framework/src/tests/Metalama.Framework.Tests.UnitTests/RunTime/RunTimeAspectHelperBufferTests.cs [hunk 4]
```diff
@@ -0,0 +1,253 @@
...
+    /// Verifies that <see cref="RunTimeAspectHelper.Buffer{T}(IEnumerator{T})"/> returns an <see cref="IEnumerator{T}"/>
+    /// that supports <see cref="IEnumerator.Reset"/>.
+    /// </summary>
+    [Fact]
+    public void BufferGenericEnumerator_ReturnsResettableEnumerator()
+    {
+        var buffered = RunTimeAspectHelper.Buffer( CreateTestEnumerator() );
+
+        // The returned enumerator should support Reset.
+        Assert.True( buffered is IEnumerator<string> );
```
[the remark this answers is not in the document]
Comment (PostSharpAgent) [reply Metalama.Framework/src/tests/Metalama.Framework.Tests.UnitTests/RunTime/RunTimeAspectHelperBufferTests.cs]: Done. Replaced `Assert.True(buffered is IEnumerator<string>)` with `Assert.IsType<RunTimeAspectHelper.Enumerator<string>>(buffered)` which verifies the concrete resettable wrapper type.

File: Metalama.Framework/src/tests/Metalama.Framework.Tests.UnitTests/RunTime/RunTimeAspectHelperBufferTests.cs [hunk 5]
```diff
@@ -0,0 +1,253 @@
...
+    /// Verifies that <see cref="RunTimeAspectHelper.Buffer(IEnumerator)"/> returns an <see cref="IEnumerator"/>
+    /// that supports <see cref="IEnumerator.Reset"/>.
+    /// </summary>
+    [Fact]
+    public void BufferUntypedEnumerator_ReturnsResettableEnumerator()
+    {
+        var buffered = RunTimeAspectHelper.Buffer( CreateTestUntypedEnumerator() );
+
+        // The returned enumerator should support Reset.
+        Assert.True( buffered is IEnumerator );
```
[the remark this answers is not in the document]
Comment (PostSharpAgent) [reply Metalama.Framework/src/tests/Metalama.Framework.Tests.UnitTests/RunTime/RunTimeAspectHelperBufferTests.cs]: Done. Replaced `Assert.True(buffered is IEnumerator)` with `Assert.IsType<RunTimeAspectHelper.Enumerator>(buffered)` which verifies the concrete resettable wrapper type.

**Review by gfraiteur — APPROVED** [review]
