### PR TITLE
Fix DI accessibility error for constructor dependencies (#744)

### LINKED ISSUE #744: Dependency injection: report an error when a dependency from a constructor to pull has lower accessibility than the constructor

### PR DESCRIPTION
**Pull request by PostSharpAgent**
## Summary
- Report a Metalama diagnostic error (LAMA0704) when a dependency type introduced via `[IntroduceDependency]` has lower accessibility than the constructor that would pull it, instead of generating invalid code that fails with CS0051.
- Added accessibility check in `DefaultDependencyInjectionStrategy.TryPullDependency` that computes effective accessibility considering nested types.
- Also fixed a pre-existing IDE0005 warning in `AspectReferenceEmptyMethodSubstitution.cs`.
- Fixes #744

## Checklist
- [x] Reproduce bug with failing regression test
- [x] Implement fix
- [x] Build and test
- [x] Finalize

## Test plan
- [x] `Issue744.cs`: Public class with internal dependency type — reports LAMA0704 error
- [x] `Issue744_InternalClass.cs`: Internal class with internal dependency type — succeeds (no accessibility issue)
- [x] All 40 existing DI aspect tests pass
- [x] All 12 ServiceLocator aspect tests pass
- [x] Zero warnings in `Build.ps1 build`

### CODE REVIEW

File: Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs [hunk 1]
```diff
@@ -163,12 +163,52 @@ protected bool TryPullDependency( IAdviser<INamedType> adviser, IFieldOrProperty
...
+
+    private static Accessibility GetEffectiveAccessibility( IType type )
+    {
+        if ( type is INamedType namedType )
+        {
+            return GetEffectiveAccessibility( (IMemberOrNamedType) namedType );
+        }
+
+        // For non-named types (arrays, pointers, etc.), assume public.
+        return Accessibility.Public;
```
Comment (gfraiteur) [inline Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: This is incorrect. Use the element type.

File: Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs [hunk 2]
```diff
@@ -163,12 +163,52 @@ protected bool TryPullDependency( IAdviser<INamedType> adviser, IFieldOrProperty
     /// <summary>
     /// Pulls the dependency from a given constructor.
     /// </summary>
+    private static Accessibility GetEffectiveAccessibility( IMemberOrNamedType member )
+    {
+        var accessibility = member.Accessibility;
+
+        for ( var declaringType = member.DeclaringType; declaringType != null; declaringType = declaringType.DeclaringType )
```
Comment (gfraiteur) [inline Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: THink of generic arguments.

File: Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs [hunk 3]
```diff
@@ -163,12 +163,52 @@ protected bool TryPullDependency( IAdviser<INamedType> adviser, IFieldOrProperty
     /// <summary>
     /// Pulls the dependency from a given constructor.
     /// </summary>
+    private static Accessibility GetEffectiveAccessibility( IMemberOrNamedType member )
+    {
```
Comment (gfraiteur) [inline Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: Should be moved as an extension method to Metalama.Framework.Code.DeclarationExtensions.

Comment (gfraiteur) [reply Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: Should have dedicated unit tests.

**Review by gfraiteur — CHANGES_REQUESTED** [review]

File: Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs (hunk 1 above)
Comment (PostSharpAgent) [reply Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: Fixed. Arrays now use `ElementType` and pointers use `PointedAtType` to compute accessibility. Added an `Issue744_Array` aspect test to verify.

File: Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs (hunk 2 above)
Comment (PostSharpAgent) [reply Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: Fixed. The `IType` overload now iterates over all `TypeArguments` of an `INamedType` and takes the minimum accessibility. Added an `Issue744_GenericArgument` aspect test and unit tests covering nested generics.

File: Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs (hunk 3 above)
Comment (PostSharpAgent) [reply Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: Done. Moved both overloads (`IMemberOrNamedType` and `IType`) to `Metalama.Framework.Code.DeclarationExtensions` as public extension methods. The DI strategy now calls them via extension method syntax.

Comment (PostSharpAgent) [reply Metalama.Extensions/src/Metalama.Extensions.DependencyInjection/Implementation/DefaultDependencyInjectionStrategy.cs]: Done. Added `GetEffectiveAccessibilityTests` with 13 unit tests covering: public/internal classes, nested types, arrays, generics with internal type arguments, nested generics, and dynamic types.

**Review by gfraiteur — APPROVED** [review]

File: Metalama.Framework/src/Metalama.Framework/Code/DeclarationExtensions.cs [hunk 4]
```diff
@@ -384,5 +385,65 @@ public static bool IsAutoPropertyBackingField( this IField field )
...
+            return accessibility;
+        }
+
+        /// <summary>
+        /// Gets the effective accessibility of a type, taking into account the accessibility of containing types,
+        /// element types (for arrays and pointers), and type arguments (for generic types).
+        /// </summary>
+        /// <param name="type">The type.</param>
+        /// <returns>The minimum effective accessibility across all component types.</returns>
+        public static Accessibility GetEffectiveAccessibility( this IType type )
```
[the remark this answers is not in the document]
Comment (gfraiteur) [reply Metalama.Framework/src/Metalama.Framework/Code/DeclarationExtensions.cs]: good point.

**Review by gfraiteur — CHANGES_REQUESTED** [review]
Address copilot's feedback.

File: Metalama.Framework/src/Metalama.Framework/Code/DeclarationExtensions.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (PostSharpAgent) [reply Metalama.Framework/src/Metalama.Framework/Code/DeclarationExtensions.cs]: Fixed. Changed the `IMemberOrNamedType` overload to `IMember` and extracted a private `GetEffectiveAccessibilityOfMemberOrNamedType` helper. Now `INamedType` unambiguously resolves to the `IType` overload with no casts needed.

— Claude for @gfraiteur

**Review by gfraiteur — APPROVED** [review]
